language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - wget
      - texlive-full

install:
  - pip install -r requirements.txt

script:
  - cookiecutter https://github.com/dvolgyes/article_template  -o . --no-input
  - make -C latex_article 
  - make -C latex_article submission